<?php

declare(strict_types=1);

/**
 * Invalidate wiki search view cache tags to use <input type="search">.
 */
function omnipedia_search_update_9401(): void {

  // @see https://gitlab.com/neurocracy/omnipedia/modules/omnipedia-search/issues/2
  // @see https://www.drupal.org/project/search_api/issues/3214236
  \Drupal::service('cache_tags.invalidator')->invalidateTags([
    'config:views.view.wiki_search',
  ]);

}

/**
 * Rebuild container, hooks, theme registry for porting Omnipedia header search.
 */
function omnipedia_search_update_9402(): void {

  \Drupal::service('kernel')->invalidateContainer();

  // This service is technically @internal but there isn't a clear API for
  // rebuilding the theme registry.
  \Drupal::service('theme.registry')->reset();

  \Drupal::service('module_handler')->resetImplementations();

}
